# Default values for globaleaks.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tsundokul/globaleaks
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  httpsPort: 443

resources:
  limits:
    cpu: 1000m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 524Mi
