apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-globaleaks
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: globaleaks
  template:
    metadata:
      labels:
        app: globaleaks
    spec:
      containers:
      - name: globaleaks
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        - name: TENANT
          value: "{{ .Release.Name }}"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
