apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.global.tenant }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.persistence.size }}
