apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: globaleaks-{{ .Release.Name }}
spec:
  serviceName: globaleaks-{{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: globaleaks
  template:
    metadata:
      labels:
        app: globaleaks
    spec:
      containers:
      - name: globaleaks
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        - name: TENANT
          value: "{{ .Values.global.tenant }}"
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
          - name: data
            mountPath: /var/globaleaks/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.global.tenant }}-pvc
